// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeSpeaker(text string) *Speaker {
	message := NewMessage(text)
	speaker := NewSpeaker(message)
	return speaker
}
